import NavBar from "@/components/NavBar/NavBar"
import { Metadata } from "next"
import './global.css'

export const metadata:Metadata = {
  title: {
    absolute: "",
    default: "Recipe Application",
    template: ""
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
          {children}
      </body>
    </html>
  )
}
